# Generated by Django 5.0.4 on 2024-06-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician_first_name', models.CharField(max_length=100)),
                ('musician_last_name', models.CharField(max_length=100)),
                ('musician_email', models.EmailField(max_length=254)),
                ('musician_number', models.CharField(max_length=15)),
                ('musician_instrument', models.CharField(choices=[('Guitar', 'Guitar'), ('Drums', 'Drums'), ('Bass', 'Bass'), ('Keyboard', 'Keyboard'), ('Vocals', 'Vocals')], max_length=20)),
            ],
        ),
    ]
